tests: phpstan adjustments + 3 phpstan fixes
- force exclude templates and vendor directories
  @vincent-peugnet: this should stop the phpstan-vscode extension
  to report errors in templates.
- fix errors that were only reported on github because of php 7.3:
  - Missing @throws JsonException annotation
  - Regex pattern is invalid: Compilation failed:
    invalid range in character class at offset 16 in pattern:
    %(src|href)="([\w-_]+(\/([\w-_])+)*\.[a-z0-9]{1,5})"%
    the regex expected a range beacause the `-` char was placed
    in between two others. +
    `\w` includes `_`
- plus one last easy error:
  PHPDoc tag @param references unknown parameter: $authorcompare